export const ADD_CASH = "ADD_CASH";
export const UPDATE_CASH_AMOUNT = "UPDATE_CASH_AMOUNT";

export const CHANGE_CAR_COLOR = "CHANGE_CAR_COLOR";

export const UPDATE_CARS_LIST = "UPDATE_CARS_LIST";
export const UPDATE_ENGINES_LIST = "UPDATE_ENGINES_LIST";
export const UPDATE_GEARBOXES_LIST = "UPDATE_GEARBOXES_LIST";

export const BUY_CAR = "BUY_CAR";
export const SELL_CAR = "SELL_CAR";

export const BUY_ENGINE = "BUY_ENGINE";
export const MOUNT_ENGINE = "MOUNT_ENGINE";

export const BUY_GEARBOX = "BUY_GEARBOX";
export const MOUNT_GEARBOX = "MOUNT_GEARBOX";

export const SELL_ENGINE = "SELL_ENGINE";
export const SELL_GEARBOX = "SELL_GEARBOX";
